slice_name: 'Errors per second ( global ) '
description: null
certified_by: null
certification_details: null
viz_type: echarts_area
params:
  datasource: 10__table
  viz_type: echarts_area
  slice_id: 9
  x_axis: time_interval
  time_grain_sqla: PT1S
  metrics:
  - aggregate: AVG
    column:
      advanced_data_type: null
      changed_on: '2024-12-23T18:49:49.692227'
      column_name: Error rate
      created_on: '2024-12-23T18:49:49.692224'
      description: null
      expression: null
      extra: '{"warning_markdown":null}'
      filterable: true
      groupby: true
      id: 47
      is_active: true
      is_dttm: false
      python_date_format: null
      type: LONGINTEGER
      type_generic: 0
      uuid: 9bf840a5-a848-47f8-8efe-c967437a1cd0
      verbose_name: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: false
    label: AVG(Error rate)
    optionName: metric_r7w146ldj3m_9r3hvn7xsiv
    sqlExpression: null
  groupby: []
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    expressionType: SIMPLE
    operator: TEMPORAL_RANGE
    subject: time_interval
  row_limit: 1000
  truncate_metric: true
  show_empty_columns: true
  comparison_type: values
  annotation_layers: []
  forecastPeriods: 10
  forecastInterval: 0.8
  x_axis_title_margin: 15
  y_axis_title_margin: 15
  y_axis_title_position: Left
  sort_series_type: sum
  color_scheme: supersetColors
  seriesType: line
  opacity: 0.2
  only_total: true
  markerSize: 6
  show_legend: true
  legendType: scroll
  legendOrientation: top
  legendMargin: ''
  x_axis_time_format: smart_date
  rich_tooltip: true
  tooltipTimeFormat: smart_date
  y_axis_format: SMART_NUMBER
  truncateXAxis: true
  y_axis_bounds:
  - null
  - null
  extra_form_data: {}
  dashboards:
  - 1
query_context: '{"datasource":{"id":10,"type":"table"},"force":false,"queries":[{"filters":[{"col":"time_interval","op":"TEMPORAL_RANGE","val":"No
  filter"}],"extras":{"time_grain_sqla":"PT1S","having":"","where":""},"applied_time_extras":{},"columns":[{"timeGrain":"PT1S","columnType":"BASE_AXIS","sqlExpression":"time_interval","label":"time_interval","expressionType":"SQL"}],"metrics":[{"aggregate":"AVG","column":{"advanced_data_type":null,"changed_on":"2024-12-23T18:49:49.692227","column_name":"Error
  rate","created_on":"2024-12-23T18:49:49.692224","description":null,"expression":null,"extra":"{\"warning_markdown\":null}","filterable":true,"groupby":true,"id":47,"is_active":true,"is_dttm":false,"python_date_format":null,"type":"LONGINTEGER","type_generic":0,"uuid":"9bf840a5-a848-47f8-8efe-c967437a1cd0","verbose_name":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"AVG(Error
  rate)","optionName":"metric_r7w146ldj3m_9r3hvn7xsiv","sqlExpression":null}],"orderby":[[{"aggregate":"AVG","column":{"advanced_data_type":null,"changed_on":"2024-12-23T18:49:49.692227","column_name":"Error
  rate","created_on":"2024-12-23T18:49:49.692224","description":null,"expression":null,"extra":"{\"warning_markdown\":null}","filterable":true,"groupby":true,"id":47,"is_active":true,"is_dttm":false,"python_date_format":null,"type":"LONGINTEGER","type_generic":0,"uuid":"9bf840a5-a848-47f8-8efe-c967437a1cd0","verbose_name":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"AVG(Error
  rate)","optionName":"metric_r7w146ldj3m_9r3hvn7xsiv","sqlExpression":null},false]],"annotation_layers":[],"row_limit":1000,"series_columns":[],"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"time_offsets":[],"post_processing":[{"operation":"pivot","options":{"index":["time_interval"],"columns":[],"aggregates":{"AVG(Error
  rate)":{"operator":"mean"}},"drop_missing_columns":false}},{"operation":"flatten"}]}],"form_data":{"datasource":"10__table","viz_type":"echarts_area","slice_id":9,"x_axis":"time_interval","time_grain_sqla":"PT1S","metrics":[{"aggregate":"AVG","column":{"advanced_data_type":null,"changed_on":"2024-12-23T18:49:49.692227","column_name":"Error
  rate","created_on":"2024-12-23T18:49:49.692224","description":null,"expression":null,"extra":"{\"warning_markdown\":null}","filterable":true,"groupby":true,"id":47,"is_active":true,"is_dttm":false,"python_date_format":null,"type":"LONGINTEGER","type_generic":0,"uuid":"9bf840a5-a848-47f8-8efe-c967437a1cd0","verbose_name":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"AVG(Error
  rate)","optionName":"metric_r7w146ldj3m_9r3hvn7xsiv","sqlExpression":null}],"groupby":[],"adhoc_filters":[{"clause":"WHERE","comparator":"No
  filter","expressionType":"SIMPLE","operator":"TEMPORAL_RANGE","subject":"time_interval"}],"row_limit":1000,"truncate_metric":true,"show_empty_columns":true,"comparison_type":"values","annotation_layers":[],"forecastPeriods":10,"forecastInterval":0.8,"x_axis_title_margin":15,"y_axis_title_margin":15,"y_axis_title_position":"Left","sort_series_type":"sum","color_scheme":"supersetColors","seriesType":"line","opacity":0.2,"only_total":true,"markerSize":6,"show_legend":true,"legendType":"scroll","legendOrientation":"top","legendMargin":"","x_axis_time_format":"smart_date","rich_tooltip":true,"tooltipTimeFormat":"smart_date","y_axis_format":"SMART_NUMBER","truncateXAxis":true,"y_axis_bounds":[null,null],"extra_form_data":{},"dashboards":[1],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: fa13373d-78ab-41db-be48-5eac1cca6f4a
version: 1.0.0
dataset_uuid: ec02e901-3061-4d05-90ca-d4dcfef9e3f0
