slice_name: Transaction response times (average)
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_line
params:
  datasource: 7__table
  viz_type: echarts_timeseries_line
  slice_id: 7
  x_axis: time_interval
  time_grain_sqla: PT1S
  x_axis_sort_asc: true
  x_axis_sort_series: name
  x_axis_sort_series_ascending: true
  metrics:
  - aggregate: AVG
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: avg
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 23
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: FLOAT
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: false
    label: AVG(avg)
    optionName: metric_53x4coaj6n9_a223qr3r767
    sqlExpression: null
  groupby:
  - name
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    expressionType: SIMPLE
    operator: TEMPORAL_RANGE
    subject: time_interval
  limit: 5
  timeseries_limit_metric:
    aggregate: AVG
    column:
      advanced_data_type: null
      changed_on: '2024-12-23T13:50:45.047335'
      column_name: avg
      created_on: '2024-12-23T13:50:37.825969'
      description: null
      expression: ''
      extra: '{}'
      filterable: true
      groupby: true
      id: 23
      is_active: true
      is_dttm: false
      python_date_format: null
      type: FLOAT
      type_generic: 0
      uuid: e46763a0-9320-4098-aeb4-63f0a269f02b
      verbose_name: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: false
    label: AVG(avg)
    optionName: metric_pclm4uznrsm_3jr632c35of
    sqlExpression: null
  order_desc: true
  row_limit: 10000
  truncate_metric: true
  show_empty_columns: true
  comparison_type: values
  annotation_layers: []
  forecastPeriods: 10
  forecastInterval: 0.8
  x_axis_title_margin: 15
  y_axis_title_margin: 150
  y_axis_title_position: Top
  sort_series_type: sum
  color_scheme: supersetColors
  seriesType: line
  area: true
  opacity: 0.2
  markerEnabled: true
  markerSize: 1
  show_legend: true
  legendType: plain
  legendOrientation: right
  legendMargin: 100
  x_axis_time_format: smart_date
  rich_tooltip: true
  tooltipTimeFormat: smart_date
  y_axis_format: DURATION
  truncateXAxis: true
  extra_form_data: {}
  dashboards:
  - 1
  - 2
  - 3
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  - 15
  - 16
  - 17
  - 18
  - 19
  - 20
  - 21
  - 22
  - 23
  - 24
  - 25
  - 26
  - 27
  - 28
  - 29
  - 30
  - 31
  - 32
  - 33
  - 34
  - 35
  - 36
  - 37
  - 38
  - 39
  - 40
  - 41
  - 42
  - 43
  - 44
  - 45
  - 46
  - 47
  - 48
  - 49
  - 50
  - 51
  - 52
  - 53
  - 54
  - 55
  - 56
  - 57
  - 58
  - 59
  - 60
  - 61
  - 62
  - 63
  - 64
  - 65
  - 66
  - 67
  - 68
  - 69
  - 70
  - 71
  - 72
  - 73
  - 74
  - 75
  - 76
  - 77
  - 78
  - 79
  - 80
  - 81
  - 82
  - 83
  - 84
  - 85
  - 86
  - 87
  - 88
  - 89
  - 90
  - 91
  - 92
  - 93
  - 94
  - 95
  - 96
  - 97
  - 98
  - 99
  - 100
  - 101
  - 102
  - 103
  - 104
  - 105
  - 106
  - 107
  - 108
  - 109
  - 110
  - 111
  - 112
  - 113
  - 114
  - 115
  - 116
  - 117
  - 118
  - 119
  - 120
  - 121
  - 122
  - 123
  - 124
  - 125
  - 126
  - 127
  - 128
  - 129
  - 130
  - 131
  - 132
  - 133
  - 134
  - 135
  - 136
  - 137
  - 138
  - 139
  - 140
  - 141
  - 142
  - 143
  - 144
  - 145
  - 146
  - 147
  - 148
  - 149
  - 150
  - 151
  - 152
  - 153
  - 154
  - 155
  - 156
  - 157
  - 158
  - 159
  - 160
  - 161
  - 162
  - 163
  - 164
  - 165
  - 166
  - 167
  - 168
  - 169
  - 170
  - 171
  - 172
  - 173
  - 174
  - 175
  - 176
  - 177
  - 178
  - 179
  - 180
  - 181
  - 182
  - 183
  - 184
  - 185
  - 186
  - 187
  - 188
  - 189
  - 190
  - 191
  - 192
  - 193
  - 194
  - 195
  - 196
  - 197
  - 198
  - 199
  - 200
  - 201
  - 202
  - 203
  - 204
  - 205
  - 206
  - 207
  - 208
  - 209
  - 210
  - 211
  - 212
  - 213
  - 214
  - 215
  - 216
  - 217
  - 218
  - 219
  - 220
  - 221
  - 222
  - 223
  - 224
  - 225
  - 226
  - 227
  - 228
  - 229
  - 230
  - 231
  - 232
  - 233
  - 234
  - 235
  - 236
  - 237
  - 238
query_context: '{"datasource":{"id":7,"type":"table"},"force":false,"queries":[{"filters":[{"col":"time_interval","op":"TEMPORAL_RANGE","val":"No
  filter"}],"extras":{"time_grain_sqla":"PT1S","having":"","where":""},"applied_time_extras":{},"columns":[{"timeGrain":"PT1S","columnType":"BASE_AXIS","sqlExpression":"time_interval","label":"time_interval","expressionType":"SQL"},"name"],"metrics":[{"aggregate":"AVG","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"avg","description":null,"expression":null,"filterable":true,"groupby":true,"id":23,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"FLOAT","type_generic":0,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"AVG(avg)","optionName":"metric_53x4coaj6n9_a223qr3r767","sqlExpression":null}],"orderby":[[{"aggregate":"AVG","column":{"advanced_data_type":null,"changed_on":"2024-12-23T13:50:45.047335","column_name":"avg","created_on":"2024-12-23T13:50:37.825969","description":null,"expression":"","extra":"{}","filterable":true,"groupby":true,"id":23,"is_active":true,"is_dttm":false,"python_date_format":null,"type":"FLOAT","type_generic":0,"uuid":"e46763a0-9320-4098-aeb4-63f0a269f02b","verbose_name":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"AVG(avg)","optionName":"metric_pclm4uznrsm_3jr632c35of","sqlExpression":null},false]],"annotation_layers":[],"row_limit":10000,"series_columns":["name"],"series_limit":5,"series_limit_metric":{"aggregate":"AVG","column":{"advanced_data_type":null,"changed_on":"2024-12-23T13:50:45.047335","column_name":"avg","created_on":"2024-12-23T13:50:37.825969","description":null,"expression":"","extra":"{}","filterable":true,"groupby":true,"id":23,"is_active":true,"is_dttm":false,"python_date_format":null,"type":"FLOAT","type_generic":0,"uuid":"e46763a0-9320-4098-aeb4-63f0a269f02b","verbose_name":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"AVG(avg)","optionName":"metric_pclm4uznrsm_3jr632c35of","sqlExpression":null},"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"time_offsets":[],"post_processing":[{"operation":"pivot","options":{"index":["time_interval"],"columns":["name"],"aggregates":{"AVG(avg)":{"operator":"mean"}},"drop_missing_columns":false}},{"operation":"rename","options":{"columns":{"AVG(avg)":null},"level":0,"inplace":true}},{"operation":"flatten"}]}],"form_data":{"datasource":"7__table","viz_type":"echarts_timeseries_line","slice_id":7,"x_axis":"time_interval","time_grain_sqla":"PT1S","x_axis_sort_asc":true,"x_axis_sort_series":"name","x_axis_sort_series_ascending":true,"metrics":[{"aggregate":"AVG","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"avg","description":null,"expression":null,"filterable":true,"groupby":true,"id":23,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"FLOAT","type_generic":0,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"AVG(avg)","optionName":"metric_53x4coaj6n9_a223qr3r767","sqlExpression":null}],"groupby":["name"],"adhoc_filters":[{"clause":"WHERE","comparator":"No
  filter","expressionType":"SIMPLE","operator":"TEMPORAL_RANGE","subject":"time_interval"}],"limit":5,"timeseries_limit_metric":{"aggregate":"AVG","column":{"advanced_data_type":null,"changed_on":"2024-12-23T13:50:45.047335","column_name":"avg","created_on":"2024-12-23T13:50:37.825969","description":null,"expression":"","extra":"{}","filterable":true,"groupby":true,"id":23,"is_active":true,"is_dttm":false,"python_date_format":null,"type":"FLOAT","type_generic":0,"uuid":"e46763a0-9320-4098-aeb4-63f0a269f02b","verbose_name":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"AVG(avg)","optionName":"metric_pclm4uznrsm_3jr632c35of","sqlExpression":null},"order_desc":true,"row_limit":10000,"truncate_metric":true,"show_empty_columns":true,"comparison_type":"values","annotation_layers":[],"forecastPeriods":10,"forecastInterval":0.8,"x_axis_title_margin":15,"y_axis_title_margin":150,"y_axis_title_position":"Top","sort_series_type":"sum","color_scheme":"supersetColors","seriesType":"line","area":true,"opacity":0.2,"markerEnabled":true,"markerSize":1,"show_legend":true,"legendType":"plain","legendOrientation":"right","legendMargin":100,"x_axis_time_format":"smart_date","rich_tooltip":true,"tooltipTimeFormat":"smart_date","y_axis_format":"DURATION","truncateXAxis":true,"extra_form_data":{},"dashboards":[1,2,3,5,6,7,8,9,10,11,12,13,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 76967fd4-5455-4f89-b71e-71b933ccb05a
version: 1.0.0
dataset_uuid: aa648d7b-243d-4f2a-a80c-c823e5c5cacf
